# Generated by Django 4.2 on 2023-04-08 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='A title for the blog instance.', max_length=50)),
                ('description', models.CharField(help_text='An optional short description of the blog instance.', max_length=150, null=True)),
                ('content', models.TextField(help_text="The blog instance's content body.")),
            ],
        ),
    ]
